# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

 development:
   secret_key_base: adfe7d208c1430442378f5eb0527dc4175dd8ebad7e164578fef4eb2a284d706825ed44079c9c4846150d12322f755e1b53a63ecfe9cab4b2882e55fb78b093c

 test:
  secret_key_base: 1eb06b513cb57e470ed7ca819016d0f87e35dc60b7c705dbfac6e29e57cbe73bb0ed7b6924d3d00dc9fd181274d22bad429d86b114d93eb4838e232892816619

# Do not keep production secrets in the repository,
# instead read values from the environment.
# production:
#    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
